#!/bin/bash

# https://devmanual.gentoo.org/tasks-reference/completion/index.html
function _nwayo_completions() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local opts=""
  local compls=""

  # Get tasks/bundles
	local tasks=$(nwayo --tasks)
  #local project_tasks=$(nwayo --projecttasks)
  #local project_bundles=$(nwayo --projectbundles)


	compls="$tasks"

  # Only add -- or - options if the user has started typing -
  [[ "$cur" == -* ]] && compls="$compls $opts"


  # Tell complete what stuff to show.
  COMPREPLY=($(compgen -W "$compls" -- "$cur"))
}

complete -o default -F _nwayo_completions nwayo
